**Importing Dependencies and Bring in Data**

In [3]:
%pip install tensorflow matplotlib sklearn

Note: you may need to restart the kernel to use updated packages.


In [4]:
import os
import pandas as pd 
import tensorflow as tf
import numpy as np

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head(10)

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   
5  00025465d4725e87  "\n\nCongratulations from me as well, use the ...      0   
6  0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
7  00031b1e95af7921  Your vandalism to the Matt Shirvington article...      0   
8  00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...      0   
9  00040093b2687caa  alignment on this subject and which are contra...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0  
5             0        0       0       0              0  
6             1        1       0       1              0  
7             0        0       0       0              0  
8             0        0       0       0              0  
9             0        0       0       0              0

In [7]:
df.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [8]:
df.iloc[7]['comment_text']

"Your vandalism to the Matt Shirvington article has been reverted.  Please don't do it again, or you will be banned."

In [9]:
df.iloc[3]['comment_text']

'"\nMore\nI can\'t make any real suggestions on improvement - I wondered if the section statistics should be later on, or a subsection of ""types of accidents""  -I think the references may need tidying so that they are all in the exact same format ie date format etc. I can do that later on, if no-one else does first - if you have any preferences for formatting style on references or want to do it yourself please let me know.\n\nThere appears to be a backlog on articles for review so I guess there may be a delay until a reviewer turns up. It\'s listed in the relevant form eg Wikipedia:Good_article_nominations#Transport  "'

In [10]:
df[df['toxic']==1].tail()

id                                       comment_text  \
159494  fef4cf7ba0012866  "\n\n our previous conversation \n\nyou fuckin...   
159514  ff39a2895fc3b40e                  YOU ARE A MISCHIEVIOUS PUBIC HAIR   
159541  ffa33d3122b599d6  Your absurd edits \n\nYour absurd edits on gre...   
159546  ffb47123b2d82762  "\n\nHey listen don't you ever!!!! Delete my e...   
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159494      1             0        1       0       1              1  
159514      1             0        0       0       1              0  
159541      1             0        1       0       1              0  
159546      1             0        0       0       1              0  
159554      1             0        1       0       1              0

**Pre-Processing the Data**

In [11]:
from tensorflow.keras.layers import TextVectorization

In [12]:
help(TextVectorization)

Help on class TextVectorization in module keras.layers.preprocessing.text_vectorization:

class TextVectorization(keras.engine.base_preprocessing_layer.PreprocessingLayer)
 |  TextVectorization(max_tokens=None, standardize='lower_and_strip_punctuation', split='whitespace', ngrams=None, output_mode='int', output_sequence_length=None, pad_to_max_tokens=False, vocabulary=None, idf_weights=None, sparse=False, ragged=False, encoding='utf-8', **kwargs)
 |  
 |  A preprocessing layer which maps text features to integer sequences.
 |  
 |  This layer has basic options for managing text in a Keras model. It
 |  transforms a batch of strings (one example = one string) into either a list
 |  of token indices (one example = 1D tensor of integer token indices) or a
 |  dense representation (one example = 1D tensor of float values representing
 |  data about the example's tokens). This layer is meant to handle natural
 |  language inputs. To handle simple string inputs (categorical strings or
 |  pr

In [13]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [14]:
df['comment_text']

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [15]:
x = df['comment_text']
y = df[df.columns[2::]].values

In [16]:
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [17]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [18]:
MAX_FEATURES = 200000 # number of words in the vocab

In [19]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES, output_sequence_length=2000, output_mode='int')

In [20]:
vectorizer.adapt(x.values)

In [21]:
vectorizer('My end-term exams are really here!')[:7]

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([   29,     1, 10814,    20,   130,    66,     0], dtype=int64)>

In [22]:
vectorized_text = vectorizer(x.values)

In [23]:
len(vectorized_text)

159571

In [24]:
vectorized_text

<tf.Tensor: shape=(159571, 2000), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [25]:
#tensorflow data pipeline
#MCSHBAP - map, cache, shuffle, prefetch 
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) #prefetch helps prevent bottlenecks

In [26]:
len(dataset) # gives the number of batches

9974

In [27]:
train = dataset.take(int(len(dataset)*0.7))
val = dataset.skip(int(len(dataset)*0.7)).take(int(len(dataset)*0.2))
test = dataset.skip(int(len(dataset)*0.9)).take(int(len(dataset)*0.1))

In [28]:
print(f"Number of Batches of Train Data : {len(train)}")
print(f"Number of Batches of Validation Data : {len(val)}")
print(f"Number of Batches of Test Data : {len(test)}")

Number of Batches of Train Data : 6981
Number of Batches of Validation Data : 1994
Number of Batches of Test Data : 997


**Create Sequential Model**

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [39]:
model = Sequential()
model.add(Embedding(MAX_FEATURES+1, 32))
model.add(Bidirectional(LSTM(32, activation='tanh')))
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(6, activation='sigmoid'))

In [43]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

In [44]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, None, 32)          6400032   
                                                                 
 bidirectional_3 (Bidirectio  (None, 64)               16640     
 nal)                                                            
                                                                 
 dense_8 (Dense)             (None, 128)               8320      
                                                                 
 dense_9 (Dense)             (None, 256)               33024     
                                                                 
 dense_10 (Dense)            (None, 128)               32896     
                                                                 
 dense_11 (Dense)            (None, 6)                 774       
                                                      

In [45]:
history = model.fit(train, epochs=1, validation_data=val)

6981/6981 [==============================] - 7566s 1s/step - loss: 0.0636 - val_loss: 0.0466


**Making Predicitions**

In [48]:
input_text = vectorizer("you freaking suck!")

In [50]:
model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 2s 2s/step


array([[0.99869204, 0.1794096 , 0.9446102 , 0.01965532, 0.8721256 ,
        0.06833409]], dtype=float32)


**Evaluate Model**

In [51]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [52]:
pre = Precision()
rec = Recall()
CatAcc = CategoricalAccuracy()

In [58]:
print(f'\n Precision: {pre.result().numpy()}, \n Recall:{rec.result().numpy()}, \n Accuracy:{CatAcc.result().numpy()}')


 Precision: 0.8462414741516113, 
 Recall:0.6090164184570312, 
 Accuracy:0.46590909361839294


In [61]:
model.save('toxicity_grader.h5')

**Test and Gradio**

In [59]:
%pip install gradio jinja2


                                              0.0/19.7 MB ? eta -:--:--
                                              0.3/19.7 MB 6.3 MB/s eta 0:00:04
     -                                        0.7/19.7 MB 7.1 MB/s eta 0:00:03
     -                                        0.9/19.7 MB 6.8 MB/s eta 0:00:03
     --                                       1.3/19.7 MB 7.3 MB/s eta 0:00:03
     ---                                      1.7/19.7 MB 7.9 MB/s eta 0:00:03
     ----                                     2.1/19.7 MB 7.6 MB/s eta 0:00:03
     -----                                    2.7/19.7 MB 8.1 MB/s eta 0:00:03
     ------                                   3.0/19.7 MB 8.1 MB/s eta 0:00:03
     -------                                  3.6/19.7 MB 8.9 MB/s eta 0:00:02
     -------                                  3.9/19.7 MB 8.7 MB/s eta 0:00:02
     ---------                                4.5/19.7 MB 8.6 MB/s eta 0:00:02
     ----------                               5.0/19.7 MB 

In [60]:
import gradio as gr 

In [62]:
model = tf.keras.models.load_model("toxicity_grader.h5")

In [64]:
input_str = vectorizer('hey i freaken hate you!')

In [65]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 2s 2s/step


In [66]:
res

array([[0.5538233 , 0.00374617, 0.118733  , 0.01460874, 0.20770796,
        0.02074156]], dtype=float32)

In [67]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [68]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

c:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
c:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:30: UserWarning: `optional` parameter is deprecated, and it has no effect
  super().__init__(
c:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\inputs.py:30: UserWarning: `numeric` parameter is deprecated, and it has no effect
  super().__init__(


In [69]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app. 

Also please ensure that your antivirus or firewall is not blocking the binary file located at: c:\Users\Dell\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\frpc_windows_amd64_v0.2


1/1 [==============================] - 0s 149ms/step
